import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"
import { Search, HelpCircle, BookOpen, MessageSquare, Video, FileText } from "lucide-react"

export default function HelpPage() {
  const faqs = [
    {
      question: "How does the AI Blog Generator work?",
      answer:
        "Our AI Blog Generator uses advanced natural language processing to create high-quality blog content. You provide a topic, select your preferred tone and style, and our AI generates a complete blog post tailored to your specifications. You can then edit and refine the content before publishing.",
    },
    {
      question: "Can I customize the AI-generated content?",
      answer:
        "Yes, absolutely! After the AI generates content, you have full control to edit, modify, or expand upon it. You can use our rich text editor to make changes, add images, and format the content to match your brand's style.",
    },
    {
      question: "How do workflows automate content creation?",
      answer:
        "Workflows allow you to automate the content creation process. You can set up recurring schedules for content generation based on specific topics, sources, or trends. The system will automatically create drafts or publish content according to your preferences.",
    },
    {
      question: "What is the Web Scraper Tool used for?",
      answer:
        "The Web Scraper Tool allows you to extract content from external websites and use it as a reference for generating your own unique content. It helps with research and can be a starting point for creating comprehensive blog posts on specific topics.",
    },
    {
      question: "How can I improve the quality of AI-generated content?",
      answer:
        "To improve the quality of AI-generated content, provide detailed instructions, use specific topics, select the appropriate tone, and review and edit the content afterward. The more specific your inputs, the better the output will be.",
    },
    {
      question: "Is the content generated by AI original and SEO-friendly?",
      answer:
        "Yes, our AI generates original content that is designed to be SEO-friendly. The content is created based on your inputs and is not copied from existing sources. You can further optimize it for SEO using our built-in tools and suggestions.",
    },
    {
      question: "Can I export or integrate the content with other platforms?",
      answer:
        "Yes, you can export your content in various formats (HTML, Markdown, plain text) or integrate directly with popular platforms like WordPress, Medium, or social media channels using our API or direct integrations.",
    },
    {
      question: "How do I manage my subscription?",
      answer:
        "You can manage your subscription from the Settings page under the Subscription tab. There, you can view your current plan, upgrade or downgrade, update payment information, and view billing history.",
    },
  ]

  return (
    <div className="container mx-auto py-6 space-y-6">
      <div className="flex flex-col gap-2">
        <h2 className="text-3xl font-bold tracking-tight">Help & Support</h2>
        <p className="text-muted-foreground">Find answers to common questions and learn how to use the platform</p>
      </div>

      <div className="relative max-w-md">
        <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
        <Input placeholder="Search for help..." className="pl-8" />
      </div>

      <Tabs defaultValue="faq" className="w-full">
        <TabsList className="w-full justify-start">
          <TabsTrigger value="faq">
            <HelpCircle className="mr-2 h-4 w-4" />
            FAQ
          </TabsTrigger>
          <TabsTrigger value="guides">
            <BookOpen className="mr-2 h-4 w-4" />
            Guides
          </TabsTrigger>
          <TabsTrigger value="videos">
            <Video className="mr-2 h-4 w-4" />
            Video Tutorials
          </TabsTrigger>
          <TabsTrigger value="support">
            <MessageSquare className="mr-2 h-4 w-4" />
            Contact Support
          </TabsTrigger>
        </TabsList>
        <TabsContent value="faq" className="mt-4 space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Frequently Asked Questions</CardTitle>
              <CardDescription>Find answers to the most common questions about AI Blog Generator</CardDescription>
            </CardHeader>
            <CardContent>
              <Accordion type="single" collapsible className="w-full">
                {faqs.map((faq, index) => (
                  <AccordionItem key={index} value={`item-${index}`}>
                    <AccordionTrigger>{faq.question}</AccordionTrigger>
                    <AccordionContent>{faq.answer}</AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="guides" className="mt-4 space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>User Guides</CardTitle>
              <CardDescription>Step-by-step guides to help you get the most out of AI Blog Generator</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4 sm:grid-cols-2">
                {[
                  {
                    title: "Getting Started Guide",
                    description: "Learn the basics of using AI Blog Generator",
                    icon: BookOpen,
                  },
                  {
                    title: "Creating Your First Blog",
                    description: "A complete walkthrough of the blog creation process",
                    icon: FileText,
                  },
                  {
                    title: "Setting Up Workflows",
                    description: "Automate your content creation with workflows",
                    icon: FileText,
                  },
                  {
                    title: "Using the Web Scraper",
                    description: "Extract and repurpose content from the web",
                    icon: FileText,
                  },
                  {
                    title: "Advanced AI Settings",
                    description: "Fine-tune the AI to match your specific needs",
                    icon: FileText,
                  },
                  {
                    title: "SEO Optimization Tips",
                    description: "Improve your content's search engine visibility",
                    icon: FileText,
                  },
                ].map((guide, index) => (
                  <Button
                    key={index}
                    variant="outline"
                    className="h-auto flex-col items-start gap-1 p-4 justify-start"
                    asChild
                  >
                    <a href="#">
                      <guide.icon className="h-5 w-5 mb-1" />
                      <div className="text-sm font-medium">{guide.title}</div>
                      <div className="text-xs text-muted-foreground">{guide.description}</div>
                    </a>
                  </Button>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="videos" className="mt-4 space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Video Tutorials</CardTitle>
              <CardDescription>Watch video tutorials to learn how to use AI Blog Generator</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-6 sm:grid-cols-2">
                {[1, 2, 3, 4].map((video) => (
                  <div key={video} className="space-y-2">
                    <div className="relative aspect-video overflow-hidden rounded-lg bg-muted">
                      <div className="absolute inset-0 flex items-center justify-center">
                        <Button variant="outline" size="icon" className="h-12 w-12 rounded-full">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            strokeWidth="2"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            className="lucide lucide-play"
                          >
                            <polygon points="5 3 19 12 5 21 5 3" />
                          </svg>
                          <span className="sr-only">Play</span>
                        </Button>
                      </div>
                    </div>
                    <h3 className="font-medium">Video Tutorial {video}</h3>
                    <p className="text-sm text-muted-foreground">Learn how to use the AI Blog Generator platform</p>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="support" className="mt-4 space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Contact Support</CardTitle>
              <CardDescription>Get help from our support team</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <label className="font-medium">Subject</label>
                <Input placeholder="E.g., Question about AI Blog Generator" />
              </div>

              <div className="space-y-2">
                <label className="font-medium">Message</label>
                <textarea
                  className="flex min-h-[120px] w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm shadow-sm placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50"
                  placeholder="Describe your issue or question in detail"
                />
              </div>

              <div className="space-y-2">
                <label className="font-medium">Priority</label>
                <select className="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
                  <option value="low">Low - General question</option>
                  <option value="medium">Medium - Need help with a feature</option>
                  <option value="high">High - Something isn't working</option>
                  <option value="urgent">Urgent - Critical issue</option>
                </select>
              </div>

              <Button className="w-full">
                <MessageSquare className="mr-2 h-4 w-4" />
                Submit Support Request
              </Button>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  )
}

